<?php
header("Content-Type: image/png");
header("Cache-Control: public, max-age=86400");
header("Expires: " . gmdate("D, d M Y H:i:s", time() + 86400) . " GMT");

$img = base64_decode(
"iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAACXBIWXMAAAsTAAALEwEAmpwYAAAC
9UlEQVR4nO3cQU7bQBiG4U8CsINJuIGSbwRG/h1YQ7E2noKGItgRZ42p1TtMTO3iNEmfB94kV2Ffm
hFhixrBUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALx3vfv+g8nl5fX1tTznOXv27EMAAAAAAAAAAAAA
AAAAAABg0u12u91eXl6er1+vBwAAAODz+RwAAADwyS+np6eXl5eXFxUV1dXVlZWVlZWZmZmZmZubm
5ubm5uampp6enp6ampoaGhoaGhoYODg4ODg4KCgoKCgoKCwsLCwsLCwsLCwsLCwsAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMB/AyB5z7A6kAMPgFJvJv1AAAAAElFTkSuQmCC"
);

echo $img;
